config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  resources :spots do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :users, only: :show
  get 'homes', to: 'homes#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :text, presence: true

  UNKNOWN_REGEX = /\A[1-5]\z/.freeze
  validates :unknown, presence: true
  validates_format_of :unknown, with: UNKNOWN_REGEX, message: 'Input one number within 1 to 5'

  belongs_to :user
  belongs_to :spot
end

app/models/spot.rb
class Spot < ApplicationRecord
  with_options presence: true do
    validates :image
    validates :title
    validates :description
  end

  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy

  # スポット検索に関するメソッド
  def self.search(search)
    if search != ''
      Spot.where('title LIKE(?)', "%#{search}%")
    else
      Spot.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  PASSWORD_REGEX = /[a-z]\d/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'Include both letters and numbers'

  has_many :spots
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @spot = Spot.find(params[:spot_id])
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to spot_path(@spot.id)
    else
      @spot = Spot.find(params[:spot_id])
      @comments = @spot.comments.includes(:user)
      render 'spots/show'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text, :unknown).merge(user_id: current_user.id, spot_id: params[:spot_id])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_spot, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, only: :edit

  def index
    @spots = Spot.all.order('created_at DESC')
  end

  def new
    @spot = Spot.new
  end

  def create
    @spot = Spot.new(spot_params)
    if @spot.save
      redirect_to spots_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @spot.comments.includes(:user)
    @unknown = @spot.comments.average(:unknown)
  end

  def edit
  end

  def update
    if @spot.update(spot_params)
      redirect_to spot_path(@spot.id)
    else
      render :edit
    end
  end

  def destroy
    if user_signed_in? && current_user.id == @spot.user_id
      @spot.destroy
      redirect_to spots_path
    else
      redirect_to spot_path(@spot.id)
    end
  end

  def search
    @spots = Spot.search(params[:keyword])
  end

  private

  def spot_params
    params.require(:spot).permit(:image, :title, :description).merge(user_id: current_user.id)
  end

  def set_spot
    @spot = Spot.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in? && current_user.id == @spot.user_id
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @name = user.name
    @profile = user.profile
    @spots = user.spots
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<div class="about-page">

  <%= render 'shared/header' %>
  <div class="about-main">
    <div class="about-content">
      <div class="about-title">
        <h1>Travel Moodとは？</h1>
      </div>

      <ul class="explanations">
        <li class="explanation">Travel Moodは、スポット投稿型SNSです。</li>
        <li class="explanation">あなたのお気に入りスポットを投稿することができます。</li>
        <li class="explanation">他のユーザーが投稿したスポットにコメントすることができます。</li>
        <li class="explanation">ユーザー同士でUnknownsを評価することで、穴場スポットが見つかるかもしれません。</li>
      </ul>

      <div class="start-btn">
        <%= link_to "Travel Moodをはじめる", new_user_registration_path, class: "start-white-btn" %>
      </div>
    </div>
  </div>

</div>

app/views/homes/top.html.erb
<div class="top-page">

  <%# ヘッダー部分 %>
  <div class="top-header">
    <div class="top-left-header">
      <% if user_signed_in? %>
        <%= link_to "Travel Mood", spots_path, class: "top-travel-mood-logo" %>
      <% else %>
        <%= link_to "Travel Mood", root_path, class: "top-travel-mood-logo" %>
      <% end %>
    </div>

    <ul class="top-right-header">
      <% if user_signed_in? %>
        <li><%= link_to current_user.name, "#", class: "top-user-name" %></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "top-sign-out" %></li>
      <% else %>
        <li><%= link_to "新規登録", new_user_registration_path, class: "top-sign-up" %></li>
        <li><%= link_to "ログイン", new_user_session_path, class: "top-sign-in" %></li>
      <% end %>
    </ul>
  </div>
  <%# ヘッダー部分/ %>

  <%= video_tag("/videos/mixkit-turquoise-blue-water-bay-from-above-5008.mp4", autoplay: :true, loop: :true, muted: :true) %>

  <div class="appear-message">
    <div class="appear-message-text">Welcome to Travel Mood.</div>
    
    <div class="about-btn">
      <% if user_signed_in? %>
        <%= link_to "START!", spots_path, class: "about-white-btn" %>
      <% else %>
        <%= link_to "START!", homes_path, class: "about-white-btn" %>
      <% end %>
    </div>
  </div>

  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelMood</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<div class="header">
  <div class="left-header">
    <% if user_signed_in? %>
      <%= link_to "Travel Mood", spots_path, class: "travel-mood-logo" %>
    <% else %>
      <%= link_to "Travel Mood", root_path, class: "travel-mood-logo" %>
    <% end %>
  </div>

  <ul class="right-header">
    <% if user_signed_in? %>
      <li><%= link_to current_user.name, user_path(current_user.id), class: "user-name" %></li>
      <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "sign-out" %></li>
    <% else %>
      <li><%= link_to "新規登録", new_user_registration_path, class: "sign-up" %></li>
      <li><%= link_to "ログイン", new_user_session_path, class: "sign-in" %></li>
    <% end %>
  </ul>
</div>

app/views/spots/_spot.html.erb
<div class="post-spot-page"> 
  <%= render 'shared/header' %>

  <%= form_with model: @spot, class: "post-spot-main", local: true do |f| %>
  
  <div class="post-form-wrap">
    <div class="post-form-group">
      <h1 class="post-form-header">スポット情報を入力</h1>
    </div>

    <%= render 'devise/shared/error_messages', model: f.object %>
    
    <%# スポット画像 %>
    <div class="img-mark-text">
      画像
    </div>

    <div class="post-form-group">
        <div class="post-img">
          <%= f.file_field :image, id:"spot-image" %>
        </div>
    </div>
    <%# スポット画像/ %>

    <%# タイトル %>
    <div class="post-form-group">
      <div class="post-form-text">
        <%= f.label :"タイトル", class: "post-text" %>
      </div>
      <%= f.text_field :title, class: "post-input-default", id: "spot_タイトル" %>
    </div>
    <%# タイトル/ %>

    <%# スポットの説明 %>
    <div class="post-form-group">
      <div class="post-form-text">
        <%= f.label :"スポット説明", class: "post-text" %>
      </div>
      <%= f.text_area :description, class: "post-description-default", id: "spot_スポット説明", placeholder: "スポットの説明（必須 1000文字まで）", rows:"7" ,maxlength:"1000" %>
    </div>
    <%# スポットの説明/ %>

    <div class="post-form-group">
      <%= f.submit "投稿", class: "post-lightblue-btn" %>
    </div>
  
  </div>
  <% end %>

</div>

app/views/spots/edit.html.erb
<%= render partial: "spot" %>

app/views/spots/index.html.erb
<div class="all-spots-page">

  <%= render 'shared/header' %>
  
  <%# スポット検索フォーム %>
  <div class="search-wrap">
    <%= form_with(url: search_spots_path, local: true, method: :get, class: "search-form") do |f| %>
      <%= f.text_field :keyword, placeholder: "スポットを検索する", class: "search-input" %>
      <%= f.submit "検索", class: "search-btn" %>
    <% end %>
  </div>
  <%# スポット検索フォーム/ %>

  <%# スポット一覧 %>
  <div class="all-spots">
    <h2 class="spot-lists-title">投稿スポット一覧</h2>
      <ul class="spot-lists">
        <% @spots.each do |spot| %>
        <li class="spot-list">

          <%# スポット画像 %>
          <%= link_to spot_path(spot.id) do %>
            <div class="spot-img-content ">
              <%= image_tag spot.image, class: "spot-img" %>
            </div>
          <% end %>
          <%# スポット画像/ %>
        
          <div class="spot-info" >
            <div class="spot-main-info">
              <%# スポットタイトル %>
              <%= link_to spot_path(spot.id) do %>
                <div class="spot-title">
                  <%= spot.title %>
                </div>
              <% end %>
              <%# スポットタイトル /%>

              <%# 投稿者 %>
              <%= link_to user_path(spot.user.id) do %>
                <div class="spot-poster">
                  <span>By.</span>
                    <%= spot.user.name %>
                </div>
              <% end %>
              <%# 投稿者/ %>
            </div>
          </div>
        
        </li>
        <% end %>
      </ul>
  </div>
  <%# スポット一覧/ %>

  <%# 投稿ボタン %>
  <div class='new-spot-btn'>
  <span class='new-spot-btn-text'>投稿する</span>
    <a href="/spots/new">
      <%= image_tag "/images/new-spot-icon.jpeg", size: '60x50' ,class: "new-spot-btn-icon" %>
    </a>
  </div>
  <%# 投稿ボタン/ %>
</div>

app/views/spots/new.html.erb
<%= render partial: "spot" %>

app/views/spots/search.html.erb
<div class="all-spots-page">

  <%= render 'shared/header' %>
  
  <%# スポット検索フォーム %>
  <div class="search-wrap">
    <%= form_with(url: search_spots_path, local: true, method: :get, class: "search-form") do |f| %>
      <%= f.text_field :keyword, placeholder: "スポットを検索する", class: "search-input" %>
      <%= f.submit "検索", class: "search-btn" %>
    <% end %>
  </div>
  <%# スポット検索フォーム/ %>

  <%# スポット一覧 %>
  <div class="all-spots">

    <%# 検索結果の有無による条件分岐 %>
    <% if @spots.length != 0 %>
      <h2 class="spot-lists-title">検索結果</h2>
    <% else %>
      <h2 class="spot-lists-title">該当するスポットはありません</h2>
      <%= link_to "スポット一覧ページへ戻る", spots_path, class: "back-spots-page" %>
    <% end %>
    <%# 検索結果の有無による条件分岐/ %>

      <ul class="spot-lists">
        <% @spots.each do |spot| %>
        <li class="spot-list">

          <%# スポット画像 %>
          <%= link_to spot_path(spot.id) do %>
            <div class="spot-img-content ">
              <%= image_tag spot.image, class: "spot-img" %>
            </div>
          <% end %>
          <%# スポット画像/ %>
        
          <div class="spot-info" >
            <div class="spot-main-info">
              <%# スポットタイトル %>
              <%= link_to spot_path(spot.id) do %>
                <div class="spot-title">
                  <%= spot.title %>
                </div>
              <% end %>
              <%# スポットタイトル /%>

              <%# 投稿者 %>
              <%= link_to user_path(spot.user.id) do %>
                <div class="spot-poster">
                  <span>By.</span>
                    <%= spot.user.name %>
                </div>
              <% end %>
              <%# 投稿者/ %>
            </div>
          </div>
        
        </li>
        <% end %>
      </ul>
  </div>
  <%# スポット一覧/ %>

  <%# 投稿ボタン %>
  <div class='new-spot-btn'>
  <span class='new-spot-btn-text'>投稿する</span>
    <a href="/spots/new">
      <%= image_tag "/images/new-spot-icon.jpeg", size: '60x50' ,class: "new-spot-btn-icon" %>
    </a>
  </div>
  <%# 投稿ボタン/ %>
</div>

app/views/spots/show.html.erb
<div class="spot-show-page">

  <%= render 'shared/header' %>

  <%# スポット詳細 %>
  <div class="spot-show">

    <%# スポットタイトル %>
    <div class="spot-show-title">
      <%= @spot.title %>
    </div>
    <%# スポットタイトル %>

    <%# スポット画像 %>
    <div class="spot-show-img">
      <%= image_tag @spot.image, class: "spot-show-img" %>

        <%# スポット画像右上のプルダウン %>
        <% if user_signed_in? && current_user.id == @spot.user_id %>
          <div class="more">
            <span><%= image_tag "/images/arrow_top.png", class: "more-list-icon" %></span>
            <ul class="more-list">
              <li class="spot-edit-btn">
                <%= link_to '編集', edit_spot_path(@spot.id) %>
              </li>
              <li class="spot-delete-btn">
                <%= link_to '削除', spot_path(@spot.id), method: :delete %>
              </li>
            </ul>
          </div>
        <% end %>
        <%# スポット画像右上のプルダウン/ %>

    </div>
    <%# スポット画像/ %>

    <%# 投稿者 %>
      <div class="spot-show-poster">
        <%= link_to user_path(@spot.user.id), class: "spot-show-poster-text" do %>
          <span>By.</span><%= @spot.user.name %>
        <% end %>
      </div>
    <%# 投稿者/ %>

    <%# スポット説明 %>
      <div class="spot-show-description">
        <%= @spot.description %>
      </div>
    <%# スポット説明/ %>

    <%# Unknowns %>
      <div class="spot-show-unknowns">
        <% if @unknown %>
          <%= "Unknowns" %> <%= @unknown.round(1) %>
        <% else %>
          <%= "Unknowns" %> <%= "未評価" %>
        <% end %>
      </div>
    <%# Unknowns/ %>

  </div>
  <%# スポット詳細/ %>

  <%# コメント投稿欄 %>
    <div class="comment-post-wrap">

      <%# 他のユーザーの投稿の場合 %>
      <% if user_signed_in? && @spot.user_id != current_user.id %>
        <%= form_with(model: [@spot, @comment], local: true, class: "post-comment-main") do |f| %>

        <%= render 'devise/shared/error_messages', model: f.object %>

          <div class="text-form-group">
            <%= f.text_area :text, placeholder: "コメントする", class: "text-input-default" %>
          </div>

          <div class="unknowns-form-group">
            <%= f.text_field :unknown, class: "unknowns-input-default" %>
            <div class="unknowns-description-text">
              Unknowns = 穴場度を1~5点で評価してみましょう
            </div>
          </div>

          <div class="comment-btn-group">
            <%= f.submit "コメント投稿", class: "comment-lightblue-btn" %>
          </div>

        <% end %>

      <% end %>
      <%# 他のユーザーの投稿の場合/ %>

    </div>
  <%# コメント投稿欄/ %>

  <%# コメント一覧 %>
    <div class="comments-wrap">
      <h3 class="comments-title">＜コメント一覧＞</h3>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <div class="comment-main-info">
            <%= comment.text %>
            By. <%= link_to comment.user.name, user_path(comment.user.id), class: "comment-user" %>
          </div>

          <div class="comment-unknown">
            Unknowns <%= comment.unknown %>
          </div>
        <% end %>
      <% end %>
    </div>
  <%# コメント一覧/ %>

</div>

app/views/users/show.html.erb
<div class="user-show-page">

  <%= render 'shared/header' %>

  <%# ユーザー情報 %>
  <div class="user-show">

    <div class="user-show-title">
      <h1 class="user-show-title-text">
        <%= @name %>さんのプロフィール
      </h1>
    </div>

    <div class="user-profile">
      <%= @profile %>
    </div>

    <%# 投稿したスポット一覧 %>
    <div class="user-show-spots">
      <h2 class="user-show-spots-title"><%= @name %>さんの投稿スポット</h2>
        <ul class="user-show-spots-lists">
          <% @spots.each do |spot| %>
            <li class="user-show-spot-list">

              <%# スポット画像 %>
              <%= link_to spot_path(spot.id) do %>
                <div class="user-show-spot-img">
                  <%= image_tag spot.image, class: "show-spot-img" %>
                </div>
              <% end %>
              <%# スポット画像 /%>

              <%# スポットタイトル %>
              <%= link_to spot_path(spot.id) do %>
                <div class="user-show-spot-title">
                  <%= spot.title %>
                </div>
              <% end %>
              <%# スポットタイトル/ %>

            </li>
          <% end %>
        </ul>
    </div>
    <%# 投稿したスポット一覧/ %>

  </div>
  <%# ユーザー情報 /%>

</div>